### ISSUE TITLE
service endpoint creation automation required for VSTS Kubernetes release 

### ISSUE THREAD

**Issue by ossentoo** [Microsoft/azuredevopslabs#110]
Thanks for these example. I went through the walk through and got my own Kubernetes instance working and deploying from VSTS.

One bugbear though is the service endpoint needs to be created in VSTS manually just after the kubernetes cluster has been created.  This means there's a manual step in between our automated process.  So, we have split our release into two environments, with an approval step in between to allow for the pause and manual intervention.  A bit hacky.

How can we automatically create the kubernetes service endpoint in VSTS using a powershell step or similar just after the cluster has been created? In this way, our release can be automated end to end.

**Comment by sriramdasbalaji** [comment]
Hi Ossentoo,

Thanks for your feedback. We will check the feasibility to automatically create kubernetes service endpoint. 

Thanks
Balaji

**Comment by sriramdasbalaji** [comment]
Hi Ossentoo,

We have updated AKS lab with new Kubernetes task in CD pipeline. Now you don't have to create AKS service endpoint. With the new task, you can select the AKS cluster from the drop-down. Please try our updated lab and let us know your feedback

Thanks
Balaji

**Comment by ossentoo** [comment]
works well. thanks
