### ISSUE TITLE
Add Dynamics365 Azure DevOps example

### ISSUE THREAD

**Issue by Anand-Moghe** [Microsoft/azuredevopslabs#176]

**Comment by sriramdasbalaji** [comment]
Hi @Anand-Moghe 

Thanks for your feedback. We will check the feasibility to add Dynamics365 -DevOps lab. 

Thanks
Balaji

**Comment by maheralkhatib10** [comment]
How or is it possible to deploy Microsoft Azure on Amazon cloud or AliBaba cloud platform. Or maybe both and have a multiple site performance???

**Comment by maheralkhatib10** [comment]
Mr Anand.sir I do appreciate your response and your help.im going to try that diffenitly and I'm hoping that it work..thx a lot

**Comment by Anand-Moghe** [comment]
@maheralkhatib10 I just want to point out to you in  most humble way as possible that you are asking wrong questions in wrong topic. This is a thread for Dynamics 365 DevOps lab sample request. You can not start a completely new issue discussion that is not related to Dynamics 365. I will appreciate if you can remove (delete) your question from this issue and ask it in www.stackoverflow.com or some similar forum.

**Comment by maheralkhatib10** [comment]
@Anand-Moghe

**Comment by maheralkhatib10** [comment]
Sure will sir.you can tell how new to this and confused navigating around.thankyou again
