### ISSUE TITLE
The link to "Deploy to Azure" is broken

### ISSUE THREAD

**Issue by snowstormlife** [Microsoft/azuredevopslabs#179]
On this page (https://github.com/Microsoft/azuredevopslabs/tree/master/labs/vstsextend/azurefunctions), under the "Create the required Azure resources" heading, the link to "Deploy to Azure" is incorrect. 

The correct link is: 
https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FMicrosoft%2Fazuredevopslabs%2Fmaster%2Flabs%2Fvstsextend%2Fazurefunctions%2Farmtemplate%2Fazuredeploy.json

**Comment by sriramdasbalaji** [comment]
Hi @snowstormlife ,

The link to "Deploy to Azure" is not broken. It will work.  Earlier our repository name was almvm. So the ''Deploy to Azure" link is pointing to that link. We will update the link with the current repository name.

Thanks
Balaji
