### ISSUE TITLE
Azure Devops Demo generator, custom template?

### ISSUE THREAD

**Issue by baatch** [Microsoft/azuredevopslabs#190]
Is it possible to create your own custom template and deploy with Azure Devops Demo?

Is Azure Devops Demo generator solution open source?

**Comment by sriramdasbalaji** [comment]
Hi Baatch,

Yes, it's possible to create your own custom templates and deploy with Azure DevOps Demo Generator. But this feature is not yet public and it's in the development phase. We will let you know once it's out for public preview.  And the Azure DevOps Demo generator source code also going to be open source soon.

Thanks
