### ISSUE TITLE
2 Typos found in Azure DevOps Labs.

### ISSUE THREAD

**Issue by gdprtcl** [Microsoft/azuredevopslabs#199]
1. _Lab_ : Package Management with Azure Artifacts. 
_Typo_ : **PAzure Artifacts**

![screenshot 58](https://user-images.githubusercontent.com/19777169/53418840-adb04e80-39fe-11e9-9caf-9db8d4047350.png)

2. _Lab_ : Modernizing your existing ASP.NET Apps with Azure. 
_Typo_ : **LoaclDB**

![screenshot 57](https://user-images.githubusercontent.com/19777169/53418878-c28ce200-39fe-11e9-8014-efd9a44d42ad.png)

**Comment by sriramdasbalaji** [comment]
Hi Partha,

Thanks for letting us know about the typos. We have fixed the typos.

Thanks
