### ISSUE TITLE
ARM Template referencing old AKS versions no longer supported

### ISSUE THREAD

**Issue by seantleonard** [Microsoft/azuredevopslabs#227]
The Azure Deploy template: https://github.com/Microsoft/azuredevopslabs/blob/master/labs/vstsextend/kubernetes/armtemplate/azuredeploy.json

References AKS Versions  (**bolded** versions that are still valid) 
1.12.5
1.12.4
1.11.7
1.11.6
**1.10.12**   
1.10.9
**1.9.11** 

The valid versions per az aks get-versions -l <location> -o table
1.12.7              
1.12.6               
1.11.9               
1.11.8              
1.10.13            
1.10.12          
1.9.11             
1.9.10 

An incorrect version results in a template validation error "_The value of parameter orchestratorProfile.OrchestratorVersion is invalid_"

**Comment by sriramdasbalaji** [comment]
Hi Sean,

Thanks for letting us know about this issue. We have updated the supported versions for AKS.

Thanks
