### ISSUE TITLE
[docker lab] SQL Server Firewall now defaults 'Allow Access to Azure Services' = false

### ISSUE THREAD

**Issue by inverted360** [microsoft/azuredevopslabs#257]
After running the docker release pipeline, the web application does not load because the SQL server defaults to no access.

...as a workaround, I added a CLI task to pipeline with
"az sql server firewall-rule create --resource-group $(ResourceGroup) --server $(SQLServerName) --name AllowAllAzureIps --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0"

[note this requires additional variables to be set]

**Comment by inverted360** [comment]
Adding note to clarify this is for docker lab: https://github.com/Microsoft/azuredevopslabs/tree/master/labs/vstsextend/docker

**Comment by inverted360** [comment]
I see that this .json (https://github.com/microsoft/azuredevopslabs/blob/master/labs/vstsextend/docker/armtemplate/azuredeploy.json) is supposed to set the firewall, but it's not included in the pipeline yaml or mentioned in the implementation guide at https://www.azuredevopslabs.com/labs/vstsextend/docker/

**Comment by sriramdasbalaji** [comment]
Hi JB,

Thanks for letting us know about the issue. We will update the release pipeline to add the firewall settings and update the lab steps to configure the connection string.

Thanks

**Comment by sriramdasbalaji** [comment]
Hi JB,

We have added Azure CLI commands to setup connection string and to add a firewall rule. 

Thanks
