### ISSUE TITLE
Filter build result by trigger

### ISSUE THREAD

**Issue by cnovel** [microsoft/azuredevopslabs#259]
The connector allows you to post on Teams the result of each build. However it isn't possible to filter them based on the trigger. Therefore the channel can be flooded due to PR builds. Would it be possible to filter by trigger (that way we can show only Individual CI and check when the master is broken). Thanks

**Comment by sriramdasbalaji** [comment]
Hi,
Now we have the [Azure Pipelines app](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/microsoft-teams?view=azure-devops) built for Microsoft Teams to easily monitor the events for your pipelines. Hope this will solve your problem.

Thanks

**Comment by sriramdasbalaji** [comment]
Hi,
Azure Pipelines with Teams app don’t have support to filter the build notifications based on a trigger at the moment.

Thanks
