### ISSUE TITLE
add in configuration steps for macbook users

### ISSUE THREAD

**Issue by brootware** [microsoft/azuredevopslabs#267]
You should add in steps for macbook users for exercise 1 too.

**Comment by sriramdasbalaji** [comment]
Hi Brucius,

Could you please mention which lab you are talking about.

Thanks

**Comment by Brucius** [comment]
Hello @sriramdasbalaji , apologies didn't realize the feedback didn't have reference as I was commenting directly from https://www.azuredevopslabs.com/labs/azuredevops/git/./

It will be the below lab within this repo.
https://github.com/microsoft/azuredevopslabs/tree/master/labs/azuredevops/git
