### ISSUE TITLE
Lab for 2017 is missing

### ISSUE THREAD

**Issue by Styxxy** [microsoft/azuredevopslabs#276]
The download url for the 2017 edition is not working anymore: https://www.azuredevopslabs.com/labs/devopsserver/devopsvmdownload/#previous-versions

Any chance for alm image for tfs2018 ?

**Comment by Styxxy** [comment]
I found the files for tfs 2017 on https://github.com/microsoft/azuredevopslabs/blob/master/labs/tfs/almvm2017url.txt . So maybe it would be good to fix the link on the website :).

**Comment by sriramdasbalaji** [comment]
Hi,

Thanks for letting us know about this. We have fixed the broken link on the website.

Thanks
