### ISSUE TITLE
Azure DevOps custom templates

### ISSUE THREAD

**Issue by khasibhatla** [microsoft/azuredevopslabs#277]
First things first, we are in awe of what you have done with the Azure DevOps demo generator. Your work is phenomenal and gets anyone to start using Azure, Azure DevOps along with third-party tools like [LaunchDarkly ](https://azuredevopsdemogenerator.azurewebsites.net/?TemplateId=77381&Name=LaunchDarkly) within an hour to 2 hours time. Thank you for providing guidance there. 

I was wondering if there is any way, we can use this template to be able to work through it to cater to other feature flagging systems as well. As per #190, I learn that there is a possibility to opensource this work; so that everyone can benefit from this. 

Would it be possible for you folks to spill some beans and let us know when we can expect the code/template to be open-sourced in the near future? 

Can't wait to hear from you!

**Comment by sriramdasbalaji** [comment]
Hi @khasibhatla ,

Azure DevOps Demo generator source code is open-source now. Below is the repo
https://github.com/microsoft/azuredevopsdemogenerator


Thanks
