### ISSUE TITLE
Task 1 - Step 11 is out of date

### ISSUE THREAD

**Issue by tjgruber** [microsoft/azuredevopslabs#289]
When I got to step 11 in Task1, what I see in my lab is different.

What this guide shows I should in step 11 of task 1 is this:
![image](https://user-images.githubusercontent.com/15575143/61531498-40da3700-aa27-11e9-8a73-7b4e043d97d0.png)

However, what I see is the following:
![image](https://user-images.githubusercontent.com/15575143/61531458-24d69580-aa27-11e9-9770-677f09b2fb73.png)

**Comment by sriramdasbalaji** [comment]
Hi,

Thanks for letting us know about this. We have updated the instructions in the lab. 

Thanks
