### ISSUE TITLE
"Test Assemblies" build step fails

### ISSUE THREAD

**Issue by gmichael27** [microsoft/azuredevopslabs#294]
After launching the VM and following the steps as written, Task 1 / Step 5 cannot be completed as the build step "Test Assemblies" fails with the following message:

`Error: The location of 'vstest.console.exe' specified 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\Extensions\TestPlatform\vstest.console.exe' does not exist.`

As it is, the lab can't be completed on the VM. I'm following the directions at:
https://www.azuredevopslabs.com/labs/devopsserver/releasemanagement/

**Comment by sriramdasbalaji** [comment]
Hi,

Thanks for letting us know about this issue. We will update the pipeline to fix the issue.

Thanks

**Comment by sriramdasbalaji** [comment]
Hi, 

We have added the instructions to fix the issue. Please check and let us know if you still face the issue.

Thanks
