### ISSUE TITLE
Labs' launch link has expired (Test Planning and Management with Azure DevOps Server 2019)

### ISSUE THREAD

**Issue by rsadlowski** [microsoft/azuredevopslabs#298]
Good day,

When I attempt to launch the referenced lab, I receive the following error message:
(Test Planning and Management with Azure DevOps Server 2019)

Error
This launch link has expired.

Any chance you can supply us with a link that works?

Thanks.

**Comment by sriramdasbalaji** [comment]
Hi,

You can use the below link to launch the DevOps server.
https://labondemand.com/AuthenticatedLaunch/38297?providerId=4

The lab instructions which will load as part of the launch vm may be different. But you can follow the lab instructions from [Test Planning and Management with Azure DevOps Server 2019](https://azuredevopslabs.com/labs/devopsserver/testmanagement/) in the same server.

Thanks

**Comment by sriramdasbalaji** [comment]
Hi,

We have fixed the broken link on the site. 

Thanks
