### ISSUE TITLE
Deployment Failed

### ISSUE THREAD

**Issue by Champetaman-zz** [microsoft/azuredevopslabs#300]
When deploying the followin error appears:

There were errors in your deployment. Error code: DeploymentFailed.
2019-08-12T15:38:00.3083919Z ##[error]At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
2019-08-12T15:38:00.3095359Z ##[error]Details:
2019-08-12T15:38:00.3095887Z ##[error]BadRequest: {
  "error": {
    "code": "InternalServerError",
    "message": "There was an unexpected InternalServerError.  Please try again later.  x-ms-correlation-request-id: 352eddc3-c619-4ca6-b197-cb6273dfda7f"
  }
} undefined

![badrequest_error](https://user-images.githubusercontent.com/11163911/62879914-c339dc00-bcf1-11e9-92e2-5d9ffc997c09.PNG)

[Deployment-Microsoft.Template.zip](https://github.com/microsoft/azuredevopslabs/files/3493400/Deployment-Microsoft.Template.zip)

**Comment by EdKaim** [comment]
Which lab is this for? What step does it fail at?

**Comment by Champetaman** [comment]
**This is from:** azuredevopslabs/labs/vstsextend/github-azurepipelines/
**Step:** 26. Select Create to start a new release

When I deploy the release it fails.

**Comment by Champetaman** [comment]
I could solve the problem.

Seems that there is a missing step on the lab. It should say that before you deploy the app you have to create an App Services Tier on Azure with the domain as it appears on the lab: githubci-web-$(environment).

Best regards.

![app service creation before deploying](https://user-images.githubusercontent.com/11163911/62909926-28b6b880-bd44-11e9-86d1-2bd1a3005f8f.PNG)
