### ISSUE TITLE
ERROR on Install Python Extension

### ISSUE THREAD

**Issue by MalteRei** [microsoft/azuredevopslabs#315]
Hi,

When trying to run the release pipeline the following error occurs during Install Python Extension phase:
"##[error]Error: Failed to install site extension 'python 3.5.3 x86'. Error: Not Found (CODE: 404)"

Does anyone know what that means and how to resolve it?

To reproduce follow:
https://www.azuredevopslabs.com/labs/vstsextend/python/

**Comment by MalteRei** [comment]
I found the solution. I had to add the Python 3.5.3 x86 extension manually from within the azure portal. I didn't know about that and thought that the tutorial was just clone and go. 
On the other hand using Python 3.6.4 x86 extension on my own project I did not have to configure it manually. It was added automatically.

**Comment by CaduceusInc** [comment]
Please how did you install it on the azure portal?

**Comment by MalteRei** [comment]
You can install extensions in the Azure portal by going to your AppService resource.
Then scroll down to the "Development Tools" section in the left-hand menu. Under the "Development Tools" section is the "Extensions" page.
![image](https://user-images.githubusercontent.com/37665562/152965154-3213cc5c-c3c5-4020-b65b-e283d6daf6b3.png)

On the "Extensions" page, click "+ Add" on top to search and add the extension you would like to add.
![image](https://user-images.githubusercontent.com/37665562/152965066-aad86dd2-2849-4528-88c0-c041a1ee9735.png)
