### ISSUE TITLE
Sign in issue to Azure DevOps Generator 

### ISSUE THREAD

**Issue by kasunsjc** [microsoft/azuredevopslabs#316]
When I try to sign in to Azure devops demo generator it doesn't redirect me to sign in page. it loads the same page. I tried few times with different browsers, but still the same issue existed

**Comment by aksh-h** [comment]
Could you please let us know which Id you were using to login? You can write to AzureDevOpsDemoGenerator@service.microsoft.com

**Comment by kasunsjc** [comment]
I'm using my hotmail ID. Thanks @aksh-h  I will write to above email !!

**Comment by aksh-h** [comment]
Do you have organization in the logged in directory?

**Comment by kasunsjc** [comment]
Yes I do

**Comment by aksh-h** [comment]
Could you please retry?

**Comment by sriramdasbalaji** [comment]
Hi,

Hope the issue is resolved. Closing this issue. 

Thanks
