### ISSUE TITLE
Is there a link on the website where I can see all the available labs?

### ISSUE THREAD

**Issue by blueelvis** [microsoft/azuredevopslabs#340]
Hi!

First of all, fantastic job with the labs!

I was wondering, is there a link where I can see all the labs which are available? Or whatever which is displayed on the home page is all what is out there?

Thanks,
Pranav

**Comment by sriramdasbalaji** [comment]
Hi Pranav,

Thanks for your encouraging feedback. Whatever is displayed on the [Home Page ](https://azuredevopslabs.com/) and [DevOpsServer page](https://azuredevopslabs.com/labs/devopsserver/) is all that we have as of now.

Thanks
