### ISSUE TITLE
Github Integration Lab has Dead Link to Calculator Demo

### ISSUE THREAD

**Issue by stevek180** [microsoft/azuredevopslabs#350]
Task 1 in this lab:
https://www.azuredevopslabs.com/labs/azuredevops/github-integration/#task-1-forking-a-github-repo-and-installing-azure-pipelines
has a dead link to the demo GitHub project ->  https://github.com/calculator-demo/calculator

**Comment by sriramdasbalaji** [comment]
Hi Stevek,

This one is outdated. Please follow the below one
https://azuredevopslabs.com/labs/vstsextend/github-azurepipelines/

Thanks
