### ISSUE TITLE
local cert issues

### ISSUE THREAD

**Issue by grahamehorner** [microsoft/azuredevopslabs#351]
Not sure if this is the correct repo to report this; however I'm seeing an issue with a local install of AzureDevOps and cloning repos in VisualStudio 2019 and using GIT at the commandline 

the error I'm seeing is 

Cloning into 'xxxxx'...
Error encountered while cloning the remote repository: Git failed with a fatal error.
unable to access 'https://xxxx/DefaultCollection/xxx/_git/xxx/': SSL certificate problem: self signed certificate

**Comment by sriramdasbalaji** [comment]
Hi,

If you are using the self-signed certificate you may face this issue.  Use below command to skip the SSL verification 

git -c http.sslVerify=false clone https://yourcloneURL

Thanks
