### ISSUE TITLE
az aks create fails on free tier

### ISSUE THREAD

**Issue by alxdembo** [microsoft/azuredevopslabs#356]
By default it fails, but could be solved as following:

`aleksandrs@Azure:~$ az aks create --resource-group rggg --name aks-ftw --generate-ssh-keys`

Operation failed with status: 'Bad Request'. Details: Provisioning of resource(s) forcontainer service aks-ftw in resource group rggg failed. Message: The operation couldn't be completed as it results in exceeding quota limit of Core. Maximum allowed: 4, Current in use: 0, Additional requested: 6. Read more about quota limits at https://aka.ms/AzurePerVMQuotaLimits. Submit a request for Quota increase using the link https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%228568a463-2d20-4541-a5fe-d0c3222217e6%22,%22pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D.. Details:

`aleksandrs@Azure:~$ az aks create --resource-group rggg --name aks-ftw --generate-ssh-keys --node-count 1`

Deployment failed. Correlation ID: 9b910dca-9db6-4e91-8287-28af37457dc5. Reconcile standard load balancer failed. Details: standardLoadBalancerReconciler retry failed: Code="MissingSubscriptionRegistration" Message="The subscription is not registered to usenamespace 'Microsoft.Network'. See https://aka.ms/rps-not-found for how to register subscriptions." Details=[{"code":"MissingSubscriptionRegistration","message":"The subscription is not registered to use namespace 'Microsoft.Network'. See https://aka.ms/rps-not-found for how to register subscriptions.","target":"Microsoft.Network"}].

`aleksandrs@Azure:~$ azure provider register Microsoft.Network`

info:    Executing command provider register
- Registering provider Microsoft.Network with subscription 8568a463-2d20-4541-a5fe-d0c+222217e6
error:   Namespace Microsoft.Network Registration took too long to complete
error:   Error information has been recorded to /home/aleksandrs/.azure/azure.err
error:   provider register command failed

`aleksandrs@Azure:~$ azure provider register Microsoft.Network`

info:    Executing command provider register
- Registering provider Microsoft.Network with subscription 8568a463-2d20-4541-a5fe-d0c+222217e6
info:    provider register command OK

`aleksandrs@Azure:~$ az aks create --resource-group rggg --name aks-ftw --generate-ssh-keys --node-count 1`

success

**Comment by sriramdasbalaji** [comment]
Hi,

This is normal behaviour with any type of subscription. If the usernamespace is not registered we need to do this.

Thanks
