### ISSUE TITLE
Configuring a CD pipeline for your Jenkins CI : Port 8080

### ISSUE THREAD

**Issue by ben-garside** [microsoft/azuredevopslabs#359]
The lab does not say that you will need to add an incoming rule to the NSG to allow access to port 8080. The method of using port tunneling is create for local access but will not work via service hook or service integration so will fail. Also if setting up the VM with SSH, the putty command provided will not work as you need to provide the private key.

**Comment by quadzz** [comment]
@ben-garside You are right, added it in https://github.com/microsoft/azuredevopslabs/pull/386
