### ISSUE TITLE
Cannot access devopsservervm2019

### ISSUE THREAD

**Issue by sudhakarau1** [microsoft/azuredevopslabs#370]
From https://www.azuredevopslabs.com/labs/devopsserver/devopsvmdownload/devopsvm2019links.txt and https://github.com/microsoft/azuredevopslabs/blob/master/labs/devopsserver/devopsvmdownload/devopsvm2019links.txt
Getting :
This site can’t be reached
devopsservervm2019.blob.core.windows.net’s server IP address could not be found.
Try:

Checking the connection
Checking the proxy, firewall, and DNS configuration
Running Windows Network Diagnostics
ERR_NAME_NOT_RESOLVED

**Comment by curriyo** [comment]
I have the same problem

**Comment by sriramdasbalaji** [comment]
Hi all,

We have fixed the broken links. Please find below the updated links
https://azuredevopslabs.com/labs/devopsserver/devopsvmdownload/devopsvm2019links.txt

Thanks
