### ISSUE TITLE
Deployment error pertaining to deprecated Kubernetes API version in mhc.yaml 

### ISSUE THREAD

**Issue by noemi616** [microsoft/azuredevopslabs#375]
Reposting this as related to [Issue 201](https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/201)

I am running the Azure DevOps labs on deploying MHC in AKS and ran into build issue when running the release pipeline. The error shows up in the "Create Deployments & Services in AKS" task as
"unable to recognize "/home/vsts/work/r1/a/MyHealth.AKS.build/deploy/mhc-aks.yaml": no matches for kind "Deployment" in version "apps/v1beta1""

, which I believe pertains to Kubernetes API "apps/v1beta1" being deprecated since 1.16. I have updated mhc.yaml to use the latest version (apps/v1) and have tried running this against Kubernetes cluster deployments running in 1.15.7 (default) as well as 1.17.0 (preview).

ARM Template may also need to be updated to latest supported AKS versions:

PS C:\windows\system32> az aks get-versions -l $region -o table
KubernetesVersion    Upgrades
-------------------  ----------------------------------------
1.17.0(preview)      None available
1.16.4(preview)      1.17.0(preview)
1.16.1(preview)      1.16.4(preview), 1.17.0(preview)
1.15.7               1.16.1(preview), 1.16.4(preview)
1.15.5               1.15.7, 1.16.1(preview), 1.16.4(preview)
1.14.8               1.15.5, 1.15.7
1.14.7               1.14.8, 1.15.5, 1.15.7
1.13.12              1.14.7, 1.14.8
1.13.11              1.13.12, 1.14.7, 1.14.8

**Comment by sriramdasbalaji** [comment]
Hi @noemi616 ,

We have fixed the api version issue in our template. You can recreate the project from demo generator to get the latest source code or replace the content of mhc-aks.yaml file from https://raw.githubusercontent.com/microsoft/azuredevopslabs/master/labs/vstsextend/kubernetes/mhc-aks.yaml

Thanks
