### ISSUE TITLE
Select the .NET Desktop with SonarCloud template not available 

### ISSUE THREAD

**Issue by sarbjitsg** [microsoft/azuredevopslabs#378]
In the Driving continuous quality of your code with SonarCloud lab, when creating a new pipeline, select the " Use the classic editor to create a pipeline without YAML. " option to see the .Net Desktop with SONARCLOUD template. Without the classic editor, the template is not available. 

The lab does not document this option.

**Comment by quadzz** [comment]
It's because when using new YAML-based editor - there is no yaml template from SonarSource included in the package.
That's why "use the classic editor" link is highlited.
