### ISSUE TITLE
Deployment failure - A credential or other secret was detected in one or more plaintext variables

### ISSUE THREAD

**Issue by jonathan-vella** [microsoft/azuredevopslabs#379]
Hello team, I cannot deploy this project https://azuredevopslabs.com/labs/vstsextend/deploymentgroups/ thru Azure Devops demo generator due to the following:

Error while creating release definition: A credential or other secret was detected in one or more plaintext variables. Remove all secrets or convert all variable types to secure. WARNING: plaintext variables are automatically inserted into script environments but secure variables are not. Any variable that is converted to a secure type must be passed as an argument or explicitly published to the environment for any script that consumes it. See https://aka.ms/1escredscan_for_pipeline_definitions for more information. If necessary, you can override this scan result on save by adding ‘**BYPASS_SECRET_SCANNING**’ to the comment field. Variables (and their corresponding stage) that need to be secured: DefaultConnectionString (Release)

**Comment by sriramdasbalaji** [comment]
Hi @jonathan-vella ,

We are not able to reproduce the issue in our Azure DevOps organization. Do you have any other information apart from the shared details.

Thanks

**Comment by jonathan-vella** [comment]
It looks like this issue is related to a security setting in the Microsoft organization. Could you perhaps apply the recommendation being displayed in the error log:

_If necessary, you can override this scan result on save by adding ‘BYPASS_SECRET_SCANNING’ to the comment field. Variables (and their corresponding stage) that need to be secured: DefaultConnectionString (Release)_

**Comment by sriramdasbalaji** [comment]
Hi @jonathan-vella ,

We have fixed this issue. Could you please retry and let us know if you still see the issue.

Thanks

**Comment by jonathan-vella** [comment]
It works! You guys rock!
