### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by MRJ28041992** [microsoft/azuredevopslabs#388]
There are several places within the instructions whereby the instructions/screenshots are not reflective of the steps which must be done. This lab needs updating ASAP as in its current state it is just unnecessarily confusing!

**Comment by sriramdasbalaji** [comment]
Hi @MRJ28041992 ,

Could you please specify which lab you are talking about.

Thanks

**Comment by sriramdasbalaji** [comment]
Hi,

Closed due to inactivity, feel free to open another ticket if the problem persists.

Thanks
