### ISSUE TITLE
Terraform lab - Terraform-CD release missing?

### ISSUE THREAD

**Issue by RubenDelange** [microsoft/azuredevopslabs#389]
Regarding the Terraform lab - cfr. https://www.azuredevopslabs.com/labs/vstsextend/terraform

I can see the Terraform-CI pipeline, but I can't find the Terraform-CD release. In fact, I can't see any release :(

Anyone else has this problem?

**Comment by sriramdasbalaji** [comment]
Hi Ruben,

Could you please try once again. We couldn't reproduce the issue. If the issue still exists, I suggest you  install [Terraform extension](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks) first and then try creating a project from Demo Generator

Thanks

**Comment by RubenDelange** [comment]
Great, that fixes it! Tyvm!
