### ISSUE TITLE
Issue in Automating your infrastructure deployments in the Cloud with Terraform and Azure Pipelines

### ISSUE THREAD

**Issue by amalgireesh** [microsoft/azuredevopslabs#393]
Issue in **Exercise 3: Deploy resources using Terraform (IaC) in Azure CD pipeline**,
In step 9, The container name **terraform** is not available.
![image](https://user-images.githubusercontent.com/48020356/75455883-db2c3100-599f-11ea-904a-b90a9ad20bb5.png)

**Comment by sriramdasbalaji** [comment]
Hi @amalgireesh ,

The container name has to be entered as **Terraform**. It won't be listed. Sorry for the confusion. We will update the instructions in the lab document.

Thanks
