### ISSUE TITLE
Excersize 2, Step 9, "select" Container terraform? Or enter?

### ISSUE THREAD

**Issue by Cyberman-tM** [microsoft/azuredevopslabs#396]
The instruction say to "select" container terraform. But there is no container terraform.
I have to manually enter it.

Did I miss a step somewhere, or is the instruction ambigous? It's a smart dropdown that can read my Azure account, so it could be either way. (Missing container or have to enter the name myself.)

**Comment by sriramdasbalaji** [comment]
Hi Cyberman,

Yes, You need to enter the Container name. We will update the instruction.

Thanks
