### ISSUE TITLE
Failed to generate deployemtGroups template project

### ISSUE THREAD

**Issue by henrynn** [microsoft/azuredevopslabs#398]
I encountered issue during creating new project basing on DeploymentGroups template and the contact mail in the webpage doesn’t exist: AzureDevOpsDemoGenerator@service.microsoft.com. 

 Diagnostic Log:
Error while creating release definition: A credential or other secret was detected in one or more plaintext variables. Remove all secrets or convert all variable types to secure. WARNING: plaintext variables are automatically inserted into script environments but secure variables are not. Any variable that is converted to a secure type must be passed as an argument or explicitly published to the environment for any script that consumes it. See https://aka.ms/1escredscan_for_pipeline_definitions for more information. If necessary, you can override this scan result on save by adding ‘**BYPASS_SECRET_SCANNING**’ to the comment field. Variables (and their corresponding stage) that need to be secured: DefaultConnectionString (Release)

**Comment by sriramdasbalaji** [comment]
Hi @henrynn ,

Thanks for letting us know about the issue. We will look into this.

Thanks

**Comment by sriramdasbalaji** [comment]
Hi @henrynn ,

Could you retry this and let us know if you still face the same issue.

Thanks

**Comment by sriramdasbalaji** [comment]
Hi @henrynn ,

We fixed this issue and verified from our end. Closing this issue for now. Please feel free to reopen if you still see the problem.

Thanks
