### ISSUE TITLE
Backlog items are not created in Part Ulimited project template

### ISSUE THREAD

**Issue by chanel1984** [microsoft/azuredevopslabs#400]
Hi, there is a problem with the Part Unlimited project template. Only test cases are created but the rest of the backlog items are not created. Please check..

**Comment by sriramdasbalaji** [comment]
Hi @chanel1984 ,

Thanks for reporting this. We will look into this.

Thanks

**Comment by sriramdasbalaji** [comment]
Hi @chanel1984,

Could you please verify once again. We fixed the issue from our end. If you still face the same issue let us know.

Thanks

**Comment by chanel1984** [comment]
thanks for the quick respond. the work items are there now.
