### ISSUE TITLE
Hands on labs unavailable

### ISSUE THREAD

**Issue by actionthomas** [microsoft/azuredevopslabs#413]
When you click on any link on the page https://azuredevopslabs.com/labs/devopsserver/handsonlabs/ you always get an error
![image](https://user-images.githubusercontent.com/1763624/80627779-b5c7ac00-8a50-11ea-9368-576427649e05.png)

**Comment by sriramdasbalaji** [comment]
Hi @actionthomas ,

Unfortunately, LaobOnDemand Virtual setups are not available now. But you can download the VM and spin up your own setup from here https://azuredevopslabs.com/labs/devopsserver/devopsvmdownload/

Thanks
