### ISSUE TITLE
Predefined variable `Build.SourceBranchName` wrong value

### ISSUE THREAD

**Issue by kohtenko** [microsoft/azuredevopslabs#414]
When branch name contains `/` symbol the value of this value is incorrect. So if the branch name is `release/1.2.3-build` the value of `Build.SourceBranchName` will be `1.2.3-build`

**Comment by sriramdasbalaji** [comment]
Hi @kohtenko ,

If you don't mind, can you share the document URL which you are referring here?

Thanks

**Comment by kohtenko** [comment]
@sriramdasbalaji https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

**Comment by sriramdasbalaji** [comment]
Hi @kohtenko ,

You need to submit feedback at the bottom of the same page.

![image](https://user-images.githubusercontent.com/13716984/81409325-90c3ef00-915c-11ea-9214-a60ea275d3a2.png)

This repo is only for [AzureDevOpsLabs](https://azuredevopslabs.com/) site related issues
Thanks
