### ISSUE TITLE
Selenium lab steps are wrong/outdated

### ISSUE THREAD

**Issue by vlad-zuga** [microsoft/azuredevopslabs#415]
For the 3rd exercise of [the Selenium lab](https://www.azuredevopslabs.com/labs/vstsextend/Selenium/) there are instructions to
![image](https://user-images.githubusercontent.com/29541452/81297686-53883000-907c-11ea-9095-2f2b3fe9b092.png)
Firstly, **C:\VSTSwinAgent** is not correct (the folder would be empty), as the agent folder is extracted to **C:\azagent\A1** (or A2, A3, etc.).
Also, there is no specification of the fact that you can register multiple agents on the same machine (specifically, both an agent in a deployment group *and* an agent for the default agent pool); instead, running *config.cmd* in the same agent folder that was set up for the deployment group (exercise 2) is going to throw an error. One needs to extract another agent folder and follow with the steps from there.

**Comment by sriramdasbalaji** [comment]
HI @vlad-zuga ,

Thanks for letting us know that C:\VSTSwinAgent is empty. In the lab, we are configuring two types of agents. One is Deployment group agent (Exercise 1) which will be configured in C:\azagent\A1 as you mentioned. But we are configuring one more agent in the interactive mode in the folder C:\VSTSWinagnent. I think some script might be not getting executed. We will look into this and update the lab.

Thanks

**Comment by sriramdasbalaji** [comment]
HI @vlad-zuga ,

We updated the lab content and demo generator template. It would be great if you can give it a try and share the feedback.

Thanks
