### ISSUE TITLE
Please fix the Controlling Deployments using Release Gates lab

### ISSUE THREAD

**Issue by cdanvergara** [microsoft/azuredevopslabs#418]
Please fix this lab, the end goal is great. But what is the purpose of doing all these steps if at the end the pipeline will fail?.
You have several comments with the error message that you obtain after completing the lab steps, there is a reply comment with a offer to fix from 8 months ago :(.

**Comment by SethJanssen** [comment]
Having the same issue. The Azure Monitor Alert task in the Canary Environment has been deprecated for a while now and breaks the deployment.

**Comment by sriramdasbalaji** [comment]
Hi all,

We updated the Release Gates template and lab instructions. Please have a look at it.

Thanks
