### ISSUE TITLE
Web app Container + MY SQL image is not available in market place. 

### ISSUE THREAD

**Issue by nirajrepo** [microsoft/azuredevopslabs#432]
Hi Team,

Please refer following lab manual which refers to Web app Container + MY SQL image which is not available in Azure Market place. Please have instructions changed to **Use Web App for Containers for the webapp and use Azure Database for MySQL to create the MySQL database.** 

https://github.com/Microsoft/azuredevopslabs/tree/master/labs/vstsextend/dockerjava/

The unclear instruction in lab has caused issues with students completing labs. Request you to fix it at the earliest.

**Comment by sriramdasbalaji** [comment]
Hi @nirajrepo ,

We have updated the lab instructions to fix the issue. Please have a look at it.

Thanks
