### ISSUE TITLE
App Center demo generator (website) is down

### ISSUE THREAD

**Issue by Styxxy** [microsoft/azuredevopslabs#438]
The App Center demo generator website (https://appcenterdemogenerator.azurewebsites.net/) seems to be down for at least 2 months.

![image](https://user-images.githubusercontent.com/1635825/88081900-58d81f80-cb81-11ea-948e-770d168805b5.png)

**Comment by sriramdasbalaji** [comment]
Hi @Styxxy ,

App Center Demo Generator site is deprecated. We will remove this lab from the site and will try to create new lab content.

Thanks

**Comment by placidseven** [comment]
2 years and the lab still has been updated.
