### ISSUE TITLE
Microsoft Hands-On Labs Profile Is Disabled

### ISSUE THREAD

**Issue by walezbee** [microsoft/azuredevopslabs#444]
The profile for connecting to the Microsoft Hands-On Labs is currently disabled. 
Kindly assist with the profile to connect to the labs.

**Comment by Midden6185** [comment]
I encounered the some problem

**Comment by Midden6185** [comment]
I encounered the same problem

**Comment by Midden6185** [comment]
I encounered the same problem

**Comment by sriramdasbalaji** [comment]
Hi all,

Unfortunately, Microsoft Hands-On Lab Virtual Environments are no longer available. You need to download Virtual Machine or you can have look at Microsoft Learn Hands-On Labs here https://docs.microsoft.com/en-us/learn/browse/?expanded=azure&products=azure-devops

Thanks
