### ISSUE TITLE
No pre commit hook

### ISSUE THREAD

**Issue by deepakkhetwal** [microsoft/azuredevopslabs#459]
I am using azuredevops, and  looking to add terraform fmt -check command to server pre commit hook, so that when developer push the code to repository, this linting tool will kick off and if error, avoid commit the code to repository. Do you have that capability at this moment?

**Comment by sriramdasbalaji** [comment]
Hi @deepakkhetwal ,

In Azure DevOps, we don't have pre-commit hook feature. Maybe you can make use of Build validation Branch Policy so that when user creates Pull request It triggers Build Pipeline (where you can kick off your tool).

Thanks
