### ISSUE TITLE
CI/CD pipeline screenshots and instructions for exercise 2 Azure Functions are incorrect

### ISSUE THREAD

**Issue by GitMje** [microsoft/azuredevopslabs#464]
For the [Azure DevOps lab for creating an Azure Function](https://www.azuredevopslabs.com/labs/vstsextend/azurefunctions/#exercise-2-create-azure-function-in-azure-portal-and-in-visual-studio), the screenshots in exercise 2  "Create Azure Function in Azure Portal and in Visual Studio" are very old.  The instructions are so old that if you're not familiar with Azure, you won't be able to follow it (which is a shame, because it's cool when you get to the end and see the site render).

For example with exercise 2, step 5, there is no `In-Portal` selection and the `Webhook + API` selection is now called `Http Trigger`.

Note, however, I was impressed with the level of work that was put into this lab, building the entire Azure DevOps Project from scratch, including work items, pipelines, etc really blew my mind.  Someone put a lot of great work into this lab and it shows, it just needs some care and feeding to stay relevant.

**Comment by sriramdasbalaji** [comment]
Hi @GitMje , 

We have updated this exercise as you suggested. Please have look at it again.

Thanks
