### ISSUE TITLE
Agile Planning and Portfolio Management with Azure Boards - Ex 1, Task 2, Step 3

### ISSUE THREAD

**Issue by MrPeanutButta** [microsoft/azuredevopslabs#478]
Tracking known issue. Will submit fix if no duplicate issue found.
This has been reported by numerous students across the official AZ-400 course delivery.

Current instructions are unclear as to where to find the **new item** widget on the overview dashboard.
Graphic showing clear steps on where to find widget on the overview dashboard would help.

**Comment by sriramdasbalaji** [comment]
Hi @MrPeanutButta ,

We have updated the screenshots. Could you please reverify and let us know if the issue still exists.

Thanks
