### ISSUE TITLE
Update Disqus

### ISSUE THREAD

**Issue by mattregul** [microsoft/azuredevopslabs#490]
There are ads appearing at the bottom of pages, which seem to be coming from Disqus and it being a "Basic" plan, which includes ads
 - https://disqus.com/pricing/

Here is the page that actually loads the Disqus content
- https://github.com/microsoft/azuredevopslabs/blob/master/_includes/disqus.html

**Options**
1. Update the Disqus plan

or

2.  Someone could just go and remove the disqus "include" from the main layout (default.html), all ads and forum features will disappear 
    - https://github.com/microsoft/azuredevopslabs/blob/0f7d44047d65193cfe12eced64b5a96adc4074de/_layouts/default.html#L223

**Comment by sriramdasbalaji** [comment]
Hi @mattregul ,

We have updated Disqus to not to show Ads.

Thanks
