### ISSUE TITLE
Can other IDE being used beside VS

### ISSUE THREAD

**Issue by zioalex** [microsoft/azuredevopslabs#496]
Reading the Demo Lab instructions ( https://azuredevopslabs.com/labs/azuredevops/prereq/ ) seems that only VS is supported.
Please clarify this.

**Comment by sriramdasbalaji** [comment]
Hi @zioalex,

The sample application which we are using in some of the labs is a .NET application, so we mentioned VS as Prerequisite only for those labs. But Azure DevOps is Platform agnostic. You can connect from any IDE.

Thanks

**Comment by monybuh** [comment]
Please update the docs to clarify it. This was not clear from the documentation.
