### ISSUE TITLE
Article out of date: https://azuredevopslabs.com/labs/vsts/monitor/

### ISSUE THREAD

**Issue by brijber** [microsoft/azuredevopslabs#501]
Usage `UseApplicationInsightsRequestTelemetry` and `UseApplicationInsightsRequestTelemetry` are deprecated.

**Comment by sriramdasbalaji** [comment]
Hi @brijber ,

The article which you have mentioned was the old one. We have updated lab on the Home Page. Try this out let us know if you face any issues
https://azuredevopslabs.com/labs/azuredevops/appinsights/
Thanks
Balaji
