### ISSUE TITLE
All labs disabled

### ISSUE THREAD

**Issue by LarryReed99** [microsoft/azuredevopslabs#510]
It looks like all of the labs are disabled.  Why?

![image](https://user-images.githubusercontent.com/49995236/106940153-322da080-66ef-11eb-8d55-644020824e05.png)

**Comment by sriramdasbalaji** [comment]
Hi @LarryReed99 ,

Azure DevOps Server Labs Virtual Environments are no more available. You need to download VM if required.

Thanks
