### ISSUE TITLE
Hands-On Lab links no longer valid

### ISSUE THREAD

**Issue by kenmuse** [microsoft/azuredevopslabs#514]
The lab links on https://github.com/microsoft/azuredevopslabs/tree/master/labs/devopsserver/handsonlabs/readme.md are no longer valid. They either redirect to the front page of Microsoft Learn (for URLs with `https://www.microsoft.com/handsonlabs/selfpacedlabs/details/{id}`) or indicate "the Lab Profile is currently disabled" (for URLs with `https://labondemand.com/AuthenticatedLaunch/{id}?providerId=4`).

**Comment by sriramdasbalaji** [comment]
Hi @kenmuse ,

Unfortunately, we don't have Azure DevOps Server Hands-On labs now. You can explore Azure DevOps services labs below https://docs.microsoft.com/en-us/learn/browse/?expanded=azure&products=azure-devops
https://azuredevopslabs.com/

Thanks
