### ISSUE TITLE
Link to Appcenter Demo Generator is not working

### ISSUE THREAD

**Issue by sajeetharan** [microsoft/azuredevopslabs#516]
App Center Demo Generator link is not working on the bottom of the page!

![image](https://user-images.githubusercontent.com/4833351/108019850-173d2380-7041-11eb-8a70-d5ddb7da289d.png)

**Comment by sriramdasbalaji** [comment]
Hi @sajeetharan ,

Unfortunately, the App Center Demo Generator is no longer available.

Thanks
