### ISSUE TITLE
PR Comments generated by SonarCloud?

### ISSUE THREAD

**Issue by JamesEarle** [microsoft/azuredevopslabs#521]
Working through this tutorial I can see that it's possible to get SonarCloud generated comments in your pull requests. I'm not getting this behaviour, do you know that this is specific to msbuild and .NET projects? I hypothesize that because we use a standalone scanner in our SonarCloud analysis it may be different. 

[Link to tutorial](https://azuredevopslabs.com/labs/vstsextend/sonarcloud/#exercise-2-analyze-sonarcloud-reports)

![image](https://user-images.githubusercontent.com/5976499/110676911-5e728c00-8189-11eb-80c3-bfc61d8a6ac3.png)

@peeter-piegaze-sonarsource or @duncanp-sonar it looks like you are contributors for this part of the document, do you have any idea?

**Comment by duncanp-sonar** [comment]
@JamesEarle the SonarSource [community forum](https://community.sonarsource.com/) is the best place to ask for help.
I believe PR commenting should work for all supported languages. However, if you are analysing C# or VB.NET code you need to use the SonarScanner for .NET for any type of analysis (i.e. "normal" CI analysis or PR analysis).

**Comment by JamesEarle** [comment]
Thanks @duncanp-sonar  I will look there. The code is Python actually so we want to use the standalone scanner, if I understand correctly
