### ISSUE TITLE
Azure DevOps Lab -- CI -- Exceeded Limit

### ISSUE THREAD

**Issue by bmoore1954** [microsoft/azuredevopslabs#529]
Hello user Simon Dickenson is reporting an issue running Continuous Integration and Continuous Development DevOps Labs which require require Pipelines.  Receiving below error:
![Azure Dev Ops Lab error_1](https://user-images.githubusercontent.com/65684490/114398744-225a8e80-9b6e-11eb-9cc8-11b83e86c57c.png)

**Comment by sriramdasbalaji** [comment]
Hi @bmoore1954 ,

Microsoft has temporarily disabled the free grant of parallel jobs for public projects and for certain private projects in new organizations. However, you can request this grant by sending an email to azpipelines-freetier@microsoft.com. Existing organizations and projects are not affected.

To request the free grant for public or private projects, send an email to azpipelines-freetier@microsoft.com and provide the following information:

- Your name
- The Azure DevOps organization for which you are seeking the free grant
- Whether you need the free grant for public projects or private projects


For more information https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=ms-hosted

Thanks
