### ISSUE TITLE
Configuring the Parts Unlimited team project - Which Organization do I select? No Permissions

### ISSUE THREAD

**Issue by TedB-MSFT** [microsoft/azuredevopslabs#530]
Hi,

I am trying to go through the Parts Unlimited Demo but every time I try to make a template I get a permissions error. Which organization do I need to select?

![image](https://user-images.githubusercontent.com/82400494/114442363-1680c380-9b92-11eb-982d-8ea3e79c119a.png)

![image](https://user-images.githubusercontent.com/82400494/114442529-4203ae00-9b92-11eb-908c-f3a34c18fb1d.png)

**Comment by edinc** [comment]
Hey @TedB-MSFT.
You need to select an organization where you have permission to create a new project.

**Comment by alicloke** [comment]
I have the same issue and do not have access to any organization.  How do I get access to one of the organizations?

**Comment by edinc** [comment]
All around organizations: https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/organization-management?view=azure-devops
Hope this helps.
