### ISSUE TITLE
 Integrate Your GitHub Projects With Azure Pipelines

### ISSUE THREAD

**Issue by zorlaski** [microsoft/azuredevopslabs#533]
This agent request is not running because you have reached the maximum number of requests that can run for parallelism type 'Microsoft-Hosted Public'. Current position in queue: 1

After task 2.5, the Job never completes, it only remains in the queue. This is the only job I have ever attempted to run.
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/61090608/115192428-ca191480-a0b8-11eb-8102-4287c8ef845e.png">

**Comment by sriramdasbalaji** [comment]
Hi @zorlaski  ,

Microsoft has temporarily disabled the free grant of parallel jobs for public projects and for certain private projects in new organizations. However, you can request this grant by sending an email to azpipelines-freetier@microsoft.com. Existing organizations and projects are not affected.

To request the free grant for public or private projects, send an email to azpipelines-freetier@microsoft.com and provide the following information:

- Your name
- The Azure DevOps organization for which you are seeking the free grant
- Whether you need the free grant for public projects or private projects


For more information https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=ms-hosted

Thanks
