### ISSUE TITLE
Pipeline Job Not Running

### ISSUE THREAD

**Issue by pr1nc317** [microsoft/azuredevopslabs#535]
![image](https://user-images.githubusercontent.com/56249492/115999835-05609980-a60b-11eb-96af-11455a4529e5.png)

**Full error :** This agent request is not running because you have reached the maximum number of requests that can run for parallelism type 'Microsoft-Hosted Private'. Current position in queue: 1

**Comment by melsatar** [comment]
Same issue

**Comment by sriramdasbalaji** [comment]
Hi @pr1nc317 ,

Microsoft has temporarily disabled the free grant of parallel jobs for public projects and for certain private projects in new organizations. However, you can request this grant by sending an email to azpipelines-freetier@microsoft.com. Existing organizations and projects are not affected.

To request the free grant for public or private projects, send an email to azpipelines-freetier@microsoft.com and provide the following information:

Your name
The Azure DevOps organization for which you are seeking the free grant
Whether you need the free grant for public projects or private projects
For more information https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=ms-hosted

Thanks

**Comment by pr1nc317** [comment]
Hi @sriramdasbalaji 
followed your steps around 9 hrs back
no repsonse from the other side over mail
and still the builds are getting queued only, not running

**Comment by pr1nc317** [comment]
Working now
