### ISSUE TITLE
I have this issue when I run the pipeline

### ISSUE THREAD

**Issue by melsatar** [microsoft/azuredevopslabs#536]
##[error]No agent found in pool Default which satisfies the following demand: visualstudio. All demands: msbuild, visualstudio, vstest, Agent.Version -gtVersion 2.144.0

I'm not sure if I should install visual studio on the virtual machine?

**Comment by sriramdasbalaji** [comment]
Hi @melsatar ,

If you are using the self-hosted agent you need to install Visual Studio on the build machine.

Thanks

**Comment by sriramdasbalaji** [comment]
Hi @melsatar ,

Hope your issue is resolved. Closing this issue. Feel free to reopen if you need further help.

Thanks
