### ISSUE TITLE
Issue with installing the Test and Feedback extension in Chrome

### ISSUE THREAD

**Issue by sahall71** [microsoft/azuredevopslabs#537]
When I install the test and feedback extension I go to Visual Studio and I receive this error TFS version you are connecting to is not supported. Use TFS 2015 and above to use in connected mode. when trying to continue with the instructions. I have installed a newer version of the TFS extensions in Visual Studio but, the error still persists. Is there a work around? I would really like to finish this lab.

**Comment by sriramdasbalaji** [comment]
Hi @sahall71 ,

[Test and Feedback](https://marketplace.visualstudio.com/items?itemName=ms.vss-exploratorytesting-web#supportedbrowsers) extension is a Browser add-on. It won't be asking you to go to Visual Studio. Please check the extension again.

Thanks
Balaji

**Comment by sriramdasbalaji** [comment]
Hi @sahall71 ,

Hope your issue resolved. Closing this issue for now. Feel free to reopen if the issue still exists.

Thanks
