### ISSUE TITLE
No hosted parallelism

### ISSUE THREAD

**Issue by jollykaur** [microsoft/azuredevopslabs#542]
Receiving this error when running the lab under the org I am the owner of and associated with my personal account. 
Organization Name: jollykaur
Name: Jolly Kaur
Email: jollykaur@hotmail.com 

No hosted parallelism has been purchased or granted. To request a free parallelism grant, please reach out to azpipelines-freetier@microsoft.com with your name and organization name

**Comment by dmckinstry** [comment]
Hi @jollykaur - This is a change to the Azure DevOps platform and not something that we can control in the labs.  To unblock and continue, you'll unfortunately need to send the email as requested.
Reference:
And in terms of messaging…
1. https://devblogs.microsoft.com/devops/change-in-azure-pipelines-grant-for-private-projects/
2. https://devblogs.microsoft.com/devops/change-in-azure-pipelines-grant-for-public-projects/

**Comment by jollykaur** [comment]
Thank you Dave! I have sent the email as requested.
