### ISSUE TITLE
403 Storage when trying to launch Azure Shell

### ISSUE THREAD

**Issue by ThePorus** [microsoft/azuredevopslabs#545]
Course: DevOps White Belt April 2021
Stage: Continuous Integration
Part: Managing technical debt with SonarQube and Azure DevOps

When I'm trying to launch an Azure Shell (signed in with my MS Employee credentials) I'm receiving that there in no storage mounted, which is required for the shell. When trying to create storage (using specific subscription) I'm receiving the 403 Storage creation error (I've asterisked my credentials)
{"error":{"code":"AuthorizationFailed","message":"The client '***********' with object id '**********' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/*******/resourcegroups/cloud-shell-storage-westeurope' or the scope is invalid. If access was recently granted, please refresh your credentials."}}

**Comment by sriramdasbalaji** [comment]
Hi @ThePorus

To manage resources in your Azure subscription you must have the minimum contributor access to the subscription. Please contact your subscription owner or administartor.

Thanks
