### ISSUE TITLE
Permissions issue when creating resource groups

### ISSUE THREAD

**Issue by ThePorus** [microsoft/azuredevopslabs#546]
Course: DevOps White Belt April 2021
Stage: Continuous Delivery
Part: Configuring CI/CD pipelines as code with YAML in Azure DevOps

When trying to create a resource group I'm receiving "You do not have permissions to create resource groups under subscription *****."
I'm using my MS employee credentials.

**Comment by sriramdasbalaji** [comment]
Hi @ThePorus 

To manage resources in your Azure subscription you must have the minimum contributor access to the subscription. 

Thanks
