### ISSUE TITLE
Error - Lab Profile Disabled

### ISSUE THREAD

**Issue by imrolii** [microsoft/azuredevopslabs#553]
This error is happening on all labs [here](https://azuredevopslabs.com/labs/devopsserver/handsonlabs/)...

![image](https://user-images.githubusercontent.com/79724190/122809904-9cbe3200-d2c6-11eb-823d-96ec8e5afa97.png)

**Comment by sriramdasbalaji** [comment]
Hi @imrolii ,

Unfortunately, we don't have Azure DevOps Server Hands-On labs now. You can explore Azure DevOps services labs below https://docs.microsoft.com/en-us/learn/browse/?expanded=azure&products=azure-devops
https://azuredevopslabs.com/

Thanks
