### ISSUE TITLE
Error running Docker Compose Task for the Kubernates Lab

### ISSUE THREAD

**Issue by montysinha7** [microsoft/azuredevopslabs#556]
The Run Service Pipeline task is hanging as it is unable to find the aspnetcore-build:1.0-2.0 Image File

Pulling ci-build (microsoft/aspnetcore-build:1.0-2.0)...
The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Searching for this file on the Docker Hub it does not exist.

**Comment by sriramdasbalaji** [comment]
Hi @montysinha7 ,

The issue was due to the deprecated docker images. We updated the images now. Please try again by creating a new project from the Demo generator and let us know if you face any issues

Thanks

**Comment by sriramdasbalaji** [comment]
Hi,

Closing this issue for now. Feel free to re-open if the issue still exists.

Thanks
