### ISSUE TITLE
Front-end error on the website

### ISSUE THREAD

**Issue by denizcantufekci** [microsoft/azuredevopslabs#557]
There is a front-end error in the **div** _col-sm-10_ class on the azuredevops page of the website. You can see the error in the screenshot.
[Get link](https://azuredevopslabs.com/labs/azuredevops/)

![Screenshot](https://user-images.githubusercontent.com/44196156/126032527-0a613e47-5e2d-42d4-80c8-f810c1fd1b27.png)

**Comment by sriramdasbalaji** [comment]
Hi @denizcantufekci ,

This is fixed.

Thanks
