### ISSUE TITLE
Azure DevOps Parallelism

### ISSUE THREAD

**Issue by Thei122** [microsoft/azuredevopslabs#558]
Cant complett the lab because of this Error. Very poor.
Not enough rights.

##[error]No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request

**Comment by sriramdasbalaji** [comment]
Hi @Thei122  - This is a change to the Azure DevOps platform and not something that we can control in the labs. To unblock and continue, you'll  need to send the email as requested.

Reference:

https://devblogs.microsoft.com/devops/change-in-azure-pipelines-grant-for-private-projects/
https://devblogs.microsoft.com/devops/change-in-azure-pipelines-grant-for-public-projects/

Thanks
