### ISSUE TITLE
Certificate expired on azuredevopslabs.com

### ISSUE THREAD

**Issue by demcost** [microsoft/azuredevopslabs#564]
Today, when I was trying to access website I notice that certificate was expired.

![image](https://user-images.githubusercontent.com/30150507/132586288-c5a93c08-c6c2-4782-9bf8-869c4d59e582.png)

**Comment by paratala-vijaymohan** [comment]
it would be great if one of  you resolve this issue?

**Comment by dmckinstry** [comment]
Hi all - I want you to know the issue is acknowledged and we're on it, but it will take a bit.  Thank you for your patience!

**Comment by demcost** [comment]
@dmckinstry thanks!

**Comment by wi5nia** [comment]
Almost a month and the cert is still not renewed... this is ridiculous...

**Comment by dmckinstry** [comment]
@wi5nia - I understand and agree.  This turned into much more than a simple fix.  We're almost there...

**Comment by gloridelmorales** [comment]
@demcost  The certificate issue has been resolved.

**Comment by demcost** [comment]
Thanks!
