### ISSUE TITLE
SSL Certificate Expiry

### ISSUE THREAD

**Issue by BanterBoy** [microsoft/azuredevopslabs#567]
The SSL Certificate for https://azuredevopslabs.com/ expired on the 8th of September.

![image](https://user-images.githubusercontent.com/600150/134802289-09131ab1-27c4-4ec7-95e5-089027015987.png)

You may want to update this as the browser is showing certificate warnings and not displaying the site.

**Comment by dmckinstry** [comment]
Hi @BanterBoy - Acknowledged.  This is being tracked in #564 so I'm going to close this one as duplicate.  Please continuing tracking status there.  Sorry about the inconvenience - you're not alone.
cc: @gloridelmorales

**Comment by gloridelmorales** [comment]
@BanterBoy The certificate issue has been resolved.

**Comment by BanterBoy** [comment]
thanks for letting me know
