### ISSUE TITLE
project creation devops dojo lab

### ISSUE THREAD

**Issue by mjeroue** [microsoft/azuredevopslabs#571]
hello,

i try to create the lab from template, and i get an error that i do not have permission to do so

step 6 from below
https://azuredevopslabs.com/labs/azuredevops/prereq/

**Comment by sriramdasbalaji** [comment]
Hi @mjeroue ,

You should have project creation permissions in the organization where you are trying to create project.
You must be a member of the Project Collection Administrators group or have the **Create new projects** permission set to **Allow**. If you're the Organization Owner, you're automatically added to the Project Collection Administrators group. If you aren't a member, get added.
Thanks
