### ISSUE TITLE
Access issue

### ISSUE THREAD

**Issue by userlabana** [microsoft/azuredevopslabs#573]
Hi, I am following an online course that requires me to use a preconfigured team project called Parts Unlimited. To get access to Parts Unlimited, I am asked to complete task 1 here: https://azuredevopslabs.com/labs/azuredevops/prereq/ 

I however run into an issue with the following diagnostic log: 
The following account does not have sufficient permissions to complete the operation: Ana Spasova. The following permissions are needed to perform this operation: Create new projects.

![Screenshot (80)](https://user-images.githubusercontent.com/93530822/139681593-bbe05442-8315-4b81-bed2-6363599c582d.png)

Please help with this. Thank you.

**Comment by sriramdasbalaji** [comment]
Hi @userlabana  ,

You should have project creation permissions in the organization where you are trying to create project.
You must be a member of the **Project Collection Administrators** group or have the **Create new projects** permission set to **Allow**. If you're the Organization Owner, you're automatically added to the Project Collection Administrators group. If you aren't a member, get added.
Thanks
