### ISSUE TITLE
Which Organization Should I Choose for the Lab 

### ISSUE THREAD

**Issue by smacar01** [microsoft/azuredevopslabs#574]
I am starting the DevOps White Belt DoJo lab for Continuous Planning. I'm trying to do Task 1: Configuring the Parts Unlimited team project. 

It asks to Select your Azure DevOps organization, but I don't have one that I know of to select. I don't know how to create an organization for this Lab. 

Can you please help? The clock is ticking and I have a limited time to complete this entire course!

**Comment by sriramdasbalaji** [comment]
HI @smacar01 ,

You can create from here 
https://azure.microsoft.com/en-in/services/devops/

https://docs.microsoft.com/bs-cyrl-ba/azure/devops/organizations/accounts/create-organization?view=azure-devops#create-an-organization

Thanks
