### ISSUE TITLE
Running pipeline failed 

### ISSUE THREAD

**Issue by emgebska** [microsoft/azuredevopslabs#575]
Running pipeline as per lab instruction is faling with the followinf error:

https://azuredevopslabs.com/labs/azuredevops/continuousintegration/
<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/emgebska/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/emgebska/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/emgebska/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/emgebska/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

Details                                            Agent job 1                                                           2 error(s), 3 warning(s)                                                                      PartsUnlimited-aspnet45\PartsUnlimited.DepValidation\PartsUnlimited.DepValidation.modelproj(36,11):         Error MSB4226: The imported project "C:\Program Files         (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         was not found. Also, tried to find         "ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         in the fallback search path(s) for $(VSToolsPath) - "C:\Program         Files (x86)\MSBuild\Microsoft\VisualStudio\v16.0" . These search         paths are defined in "C:\Program Files (x86)\Microsoft Visual         Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe.Config".         Confirm that the path in the <Import> declaration is correct, and         that the file exists on disk in one of the search paths.                                                                       Process 'msbuild.exe'         exited with code '1'. | Details | Agent job 1                                                           2 error(s), 3 warning(s)                                                                      PartsUnlimited-aspnet45\PartsUnlimited.DepValidation\PartsUnlimited.DepValidation.modelproj(36,11):         Error MSB4226: The imported project "C:\Program Files         (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         was not found. Also, tried to find         "ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         in the fallback search path(s) for $(VSToolsPath) - "C:\Program         Files (x86)\MSBuild\Microsoft\VisualStudio\v16.0" . These search         paths are defined in "C:\Program Files (x86)\Microsoft Visual         Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe.Config".         Confirm that the path in the <Import> declaration is correct, and         that the file exists on disk in one of the search paths.                                                                       Process 'msbuild.exe'         exited with code '1'. | Agent job 1 | 2 error(s), 3 warning(s)                                                                      PartsUnlimited-aspnet45\PartsUnlimited.DepValidation\PartsUnlimited.DepValidation.modelproj(36,11):         Error MSB4226: The imported project "C:\Program Files         (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         was not found. Also, tried to find         "ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         in the fallback search path(s) for $(VSToolsPath) - "C:\Program         Files (x86)\MSBuild\Microsoft\VisualStudio\v16.0" . These search         paths are defined in "C:\Program Files (x86)\Microsoft Visual         Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe.Config".         Confirm that the path in the <Import> declaration is correct, and         that the file exists on disk in one of the search paths.                                                                       Process 'msbuild.exe'         exited with code '1'. | 2 error(s), 3 warning(s) |   | PartsUnlimited-aspnet45\PartsUnlimited.DepValidation\PartsUnlimited.DepValidation.modelproj(36,11):         Error MSB4226: The imported project "C:\Program Files         (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         was not found. Also, tried to find         "ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         in the fallback search path(s) for $(VSToolsPath) - "C:\Program         Files (x86)\MSBuild\Microsoft\VisualStudio\v16.0" . These search         paths are defined in "C:\Program Files (x86)\Microsoft Visual         Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe.Config".         Confirm that the path in the <Import> declaration is correct, and         that the file exists on disk in one of the search paths. |   | Process 'msbuild.exe'         exited with code '1'.
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Details
Agent job 1                                                           2 error(s), 3 warning(s)                                                                      PartsUnlimited-aspnet45\PartsUnlimited.DepValidation\PartsUnlimited.DepValidation.modelproj(36,11):         Error MSB4226: The imported project "C:\Program Files         (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         was not found. Also, tried to find         "ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         in the fallback search path(s) for $(VSToolsPath) - "C:\Program         Files (x86)\MSBuild\Microsoft\VisualStudio\v16.0" . These search         paths are defined in "C:\Program Files (x86)\Microsoft Visual         Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe.Config".         Confirm that the path in the <Import> declaration is correct, and         that the file exists on disk in one of the search paths.                                                                       Process 'msbuild.exe'         exited with code '1'. | Agent job 1 | 2 error(s), 3 warning(s)                                                                      PartsUnlimited-aspnet45\PartsUnlimited.DepValidation\PartsUnlimited.DepValidation.modelproj(36,11):         Error MSB4226: The imported project "C:\Program Files         (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         was not found. Also, tried to find         "ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         in the fallback search path(s) for $(VSToolsPath) - "C:\Program         Files (x86)\MSBuild\Microsoft\VisualStudio\v16.0" . These search         paths are defined in "C:\Program Files (x86)\Microsoft Visual         Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe.Config".         Confirm that the path in the <Import> declaration is correct, and         that the file exists on disk in one of the search paths.                                                                       Process 'msbuild.exe'         exited with code '1'. | 2 error(s), 3 warning(s) |   | PartsUnlimited-aspnet45\PartsUnlimited.DepValidation\PartsUnlimited.DepValidation.modelproj(36,11):         Error MSB4226: The imported project "C:\Program Files         (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         was not found. Also, tried to find         "ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         in the fallback search path(s) for $(VSToolsPath) - "C:\Program         Files (x86)\MSBuild\Microsoft\VisualStudio\v16.0" . These search         paths are defined in "C:\Program Files (x86)\Microsoft Visual         Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe.Config".         Confirm that the path in the <Import> declaration is correct, and         that the file exists on disk in one of the search paths. |   | Process 'msbuild.exe'         exited with code '1'.
Agent job 1
2 error(s), 3 warning(s)                                                                      PartsUnlimited-aspnet45\PartsUnlimited.DepValidation\PartsUnlimited.DepValidation.modelproj(36,11):         Error MSB4226: The imported project "C:\Program Files         (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         was not found. Also, tried to find         "ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         in the fallback search path(s) for $(VSToolsPath) - "C:\Program         Files (x86)\MSBuild\Microsoft\VisualStudio\v16.0" . These search         paths are defined in "C:\Program Files (x86)\Microsoft Visual         Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe.Config".         Confirm that the path in the <Import> declaration is correct, and         that the file exists on disk in one of the search paths.                                                                       Process 'msbuild.exe'         exited with code '1'. | 2 error(s), 3 warning(s) |   | PartsUnlimited-aspnet45\PartsUnlimited.DepValidation\PartsUnlimited.DepValidation.modelproj(36,11):         Error MSB4226: The imported project "C:\Program Files         (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         was not found. Also, tried to find         "ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         in the fallback search path(s) for $(VSToolsPath) - "C:\Program         Files (x86)\MSBuild\Microsoft\VisualStudio\v16.0" . These search         paths are defined in "C:\Program Files (x86)\Microsoft Visual         Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe.Config".         Confirm that the path in the <Import> declaration is correct, and         that the file exists on disk in one of the search paths. |   | Process 'msbuild.exe'         exited with code '1'.
2 error(s), 3 warning(s)
  | PartsUnlimited-aspnet45\PartsUnlimited.DepValidation\PartsUnlimited.DepValidation.modelproj(36,11):         Error MSB4226: The imported project "C:\Program Files         (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         was not found. Also, tried to find         "ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"         in the fallback search path(s) for $(VSToolsPath) - "C:\Program         Files (x86)\MSBuild\Microsoft\VisualStudio\v16.0" . These search         paths are defined in "C:\Program Files (x86)\Microsoft Visual         Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe.Config".         Confirm that the path in the <Import> declaration is correct, and         that the file exists on disk in one of the search paths.
  | Process 'msbuild.exe'         exited with code '1'.

</body>

</html>

**Comment by sriramdasbalaji** [comment]
Hi,

Kindly let us know the Agent Specification used in the build pipeline.

Thanks

**Comment by binuverghese** [comment]
Hi,

I'm getting the same error. It fails while building the solution. Agent: Hosted agent, Pool: Azure Pipelines. Please advise and thank you.

**Comment by binuverghese** [comment]
okay so I fixed it by changing the pool image to vs2017-win2016. It was windows 2019 earlier. Build successful. Thank you!
