### ISSUE TITLE
Continuous Planning lab - no rights

### ISSUE THREAD

**Issue by RaquelMostaza** [microsoft/azuredevopslabs#576]
I do not have the appropriate access rights to perform the prerequisites of the "Continuous Planning lab". In the last step, create a new project, I receive the following message:
"The following account does not have sufficient permissions to complete the operation: XX. The following permissions are needed to perform this operation: Create new projects."

What should I do?

**Comment by RaquelMostaza** [comment]
Already answered

**Comment by smacar01** [comment]
What is the answer??? Where do I find it?

**Comment by RaquelMostaza** [comment]
Hi smacar01, I saw that there are 3 or more "closed issues" that asked this question and because of that I closed it. The answer provided does not detail a lot what to do though, but you can have a look.
For me it works now, what I did is I went to Azure DevOps (following link):
https://go.microsoft.com/fwlink/?LinkId=307137
And I logged in with my Microsoft account. This created an organization which is called like my alias, and it is the one I am using for the labs.
