### ISSUE TITLE
Lab missing menu item for Retention

### ISSUE THREAD

**Issue by Norsk1** [microsoft/azuredevopslabs#579]
Working through the Azure Devops lab for the White belt dojo course and for the continuous integration pieces my lab does not have a menu for retention settings causing me to be stuck 
![image](https://user-images.githubusercontent.com/95171574/143767471-904799a4-b823-487d-86c0-bc5312ed715e.png)

**Comment by smacar01** [comment]
I’m running into the same error for the CI lab in instructions for step 13. 

There have been multiple issues with the labs for this course so far. Response to these issues has been slow. 

**We should ALL be given an extension to the deadlline for completion! Mine deadline is December 20th.**

![Retention Instructions](https://user-images.githubusercontent.com/58864272/143949232-92f0e7ba-3927-41a2-a9d1-2c5ad0e0ac7e.png)

**Comment by sriramdasbalaji** [comment]
Hi,

You can skip this step since the retention settings are moved to project settings and Organization settings. We will remove this step from lab.

Thanks

**Comment by smacar01** [comment]
Thanks @sriramdasbalaji . What about the remaining steps in Task 1 (steps 14-17)? should we skip those too?
