### ISSUE TITLE
CI Lab Task 2, Step1-4 Build Job Fails 

### ISSUE THREAD

**Issue by smacar01** [microsoft/azuredevopslabs#582]
Now the Pipeline build job failed. I have no idea how to fix it.  What do I do now?

![image](https://user-images.githubusercontent.com/58864272/144081288-b369b58a-72da-4817-9b6c-69f5602ac3c5.png)

**Comment by sriramdasbalaji** [comment]
Hi @smacar01 ,

Could you please check the Agent specification in your build pipeline? Can you try with vs2017-win2016?
And also Can I know when did you create this project?

Thanks

**Comment by smacar01** [comment]
I have no idea what what you mean by "agent specification"  or "VS2017 win2016".

I created this project in the last 30 days.

Is it possible to have a call to explain?

Regards, Steve
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sriramdasbalaji** [comment]
Hi @smacar01 ,

Edit your Build Pipeline and select the agent as shown below
![image](https://user-images.githubusercontent.com/13716984/144236937-a31ada06-8183-4194-b39b-93cd2c2c9d5c.png)

Thanks

**Comment by smacar01** [comment]
Hi @sriramdasbalaji ,
Thanks, the build was successful.  

Unfortunately, the Task 3, Steps 2 and 3 do not reflect what's in my repo: 
Instructions:    
![image](https://user-images.githubusercontent.com/58864272/144267076-a128c702-40f7-435b-a2e8-a584de7d950c.png)

My results:
![image](https://user-images.githubusercontent.com/58864272/144267199-c5e8f71d-ecb7-47d1-b8de-01cf7131b6df.png)

I don't see a file called "Index.cshtml" in my contents to edit.

**Comment by sriramdasbalaji** [comment]
> Hi @sriramdasbalaji , Thanks, the build was successful.
> 
> Unfortunately, the Task 3, Steps 2 and 3 do not reflect what's in my repo: Instructions: ![image](https://user-images.githubusercontent.com/58864272/144267076-a128c702-40f7-435b-a2e8-a584de7d950c.png)
> 
> My results: ![image](https://user-images.githubusercontent.com/58864272/144267199-c5e8f71d-ecb7-47d1-b8de-01cf7131b6df.png)
> 
> I don't see a file called "Index.cshtml" in my contents to edit.

Hi @smacar01 , You need to navigate to the path mentioned. i.e open **src** folder then **PartsUnlimitedWebsite** folder in side this Views, Home.

Thanks
