### ISSUE TITLE
No Option for Web App + SQL in Azure Marketplace

### ISSUE THREAD

**Issue by AndrewGoodson** [microsoft/azuredevopslabs#583]
## No Web App + SQL Option to Select
When doing the Configuring CI/CD Pipelines as Code with YAML in Azure DevOps lab for LED, I am searching for Web App + SQL in the marketplace but can not find it. I have found Web App + Database but I don't think this is compatible with the web app we need to deploy. 
What other resource can we use instead of Web App + SQL in Marketplace? 

Lab Link:  [Configuring CI/CD Pipelines as Code with YAML in Azure DevOps](https://azuredevopslabs.com/labs/azuredevops/yaml/)

**Comment by sriramdasbalaji** [comment]
Hi @AndrewGoodson ,

Looks like in the portal this option is removed now. You can create a separate web app and SQL database. We will have the lab updated with the instructions.

Thanks

**Comment by sriramdasbalaji** [comment]
Hi,

This lab is updated with the required instructions. Please check.

Thanks
