### ISSUE TITLE
New Issue: Exercise - Version Control with Git - Exercise 1 Task 1 is failing

### ISSUE THREAD

**Issue by smacar01** [microsoft/azuredevopslabs#586]
Continuing to get issues/errors : Git Exercise 1, Task 1 is failing for me. Instructions:
![image](https://user-images.githubusercontent.com/58864272/144451669-b3188a36-f0d7-4eed-9f69-f8696be28204.png)

My results:
![image](https://user-images.githubusercontent.com/58864272/144451759-6f92e4cd-2830-461e-820b-23cdc4e0f73a.png)

**_**I am not familiar with Visual Studio, C# coding. I believe I have all the prerequisites loaded on my laptop. Again can not proceed further!**_**

**Comment by sriramdasbalaji** [comment]
Hi @smacar01 ,

Looks like you missed to install prerequisite Git For Windows https://gitforwindows.org/

Thanks
