### ISSUE TITLE
CI Lab - Job fails in Test Assemblies Task

### ISSUE THREAD

**Issue by RochishnaA** [microsoft/azuredevopslabs#587]
![image](https://user-images.githubusercontent.com/95436557/144470385-0541c50e-92b1-44a5-bf3f-e1f6fd13c605.png)

**Comment by smacar01** [comment]
Looks like the same problem I had. Check out their response to me in Issue #582 

After applying the changes suggested, the build worked for me.

**Comment by RochishnaA** [comment]
Hi @smacar01 , Thanks for the response.  I already have the agent specification set as "VS2017 win2016". Still it fails in Test Assemblies step. Please suggest if any idea.

**Comment by RochishnaA** [comment]
Any updates on the above one please?

**Comment by sriramdasbalaji** [comment]
Hi @RochishnaA ,

Can you try with following changes
`<Reference Include="Castle.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Castle.Core.3.3.0\lib\net45\Castle.Core.dll</HintPath>
    </Reference>`
![image](https://user-images.githubusercontent.com/13716984/145145969-6e0c9e13-343e-4854-a47a-37d89381130e.png)

`<package id="Castle.Core" version="3.3.0" targetFramework="net452" />`
![image](https://user-images.githubusercontent.com/13716984/145146104-cf930c4c-64d3-4a4d-ae15-9f32c93a4e26.png)

`  <bindingRedirect oldVersion="0.0.0.0-3.3.0.0" newVersion="4.0.0.0" />`
![image](https://user-images.githubusercontent.com/13716984/145146200-e49434d2-d6a8-467d-b7d8-87791d3aba9e.png)

**Comment by DanEvansBI** [comment]
I'm getting a different build error on any pipleline run after the first one.  I did apply the changes to "Castle.Core" as recommended by @sriramdasbalaji

2021-12-09T17:16:04.8095637Z Done Building Project "D:\a\1\s\PartsUnlimited-aspnet45\test\FabrikamFiber.SeleniumTests\FabrikamFiber.SeleniumTests.csproj" (default targets).
_2021-12-09T17:16:04.8262400Z ##[error]PartsUnlimited-aspnet45\PartsUnlimited.DepValidation\PartsUnlimited.DepValidation.modelproj(36,11): Error MSB4226: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets" was not found. Also, tried to find "ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets" in the fallback search path(s) for $(VSToolsPath) - "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v16.0" . These search paths are defined in "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe.Config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths._

**Comment by DanEvansBI** [comment]
So was able to finally get the pipeline to complete by making the following adjustments:
Restore Castle.Core reference back to 3.3.0.0 from 4.0.0.0
In the Pipeline Task Settings, the Build Solution option for "Visual Studio Version" set to Visual Studio 2017.
In the Pipeline Task Settings, the Test Assemblies option for "Test Platform Version" set to Visual Studio 2017.

**Comment by RochishnaA** [comment]
Thanks Much ! It is resolved after making changes as suggested by @sriramdasbalaji .
