### ISSUE TITLE
Repository "PartsUnlimited" is disabled

### ISSUE THREAD

**Issue by ChiaraChiapponi** [microsoft/azuredevopslabs#593]
Could anyone please explain me how to enable it?
Thanks
C

**Comment by sriramdasbalaji** [comment]
Hi @ChiaraChiapponi ,

Could you please share more details about the issue.

Thanks

**Comment by sriramdasbalaji** [comment]
Hi,

We are closing this issue, as we didn't get more information. 

Thanks
