### ISSUE TITLE
LaunchDarkly - Xproj project files are no longer supported.

### ISSUE THREAD

**Issue by HMLTC** [microsoft/azuredevopslabs#597]
I am running into this errors after cloning the Repo in the Launchdarkly project. Because of this I cannot complete task 1.

**PartsUnlimited.Models**
Message
src\PartsUnlimited.Models\PartsUnlimited.Models.xproj: Xproj project files are no longer supported. For details on migrating to csproj see https://docs.microsoft.com/dotnet/core/migration/.
**PartsUnlimited.UnitTests**
Message
test\PartsUnlimited.UnitTests\PartsUnlimited.UnitTests.xproj: Xproj project files are no longer supported. For details on migrating to csproj see https://docs.microsoft.com/dotnet/core/migration/.
**PartsUnlimitedEnv**
Message
env\PartsUnlimitedEnv.deployproj: The application which this project type is based on was not found. Please try this link for further information: https://go.microsoft.com/fwlink/?LinkId=661331&projecttype=151D2E53-A2C4-4D7D-83FE-D05416EBD58E
**PartsUnlimitedWebsite**
Message
src\PartsUnlimitedWebsite\PartsUnlimitedWebsite.xproj: Xproj project files are no longer supported. For details on migrating to csproj see https://docs.microsoft.com/dotnet/core/migration/.

**Comment by sriramdasbalaji** [comment]
Hi @HMLTC ,

You need to switch to a branch called **launch-darkly** in your repo.
![image](https://user-images.githubusercontent.com/13716984/147433955-0e93a19b-455d-4f44-a94a-6fd0510d0035.png)

Thanks
