### ISSUE TITLE
[Build failed] Parts Unlimited-ASP.NET-CI - PartsUnlimited:master - Parts Unlimited - 8086ee35

### ISSUE THREAD

**Issue by ricardosas** [microsoft/azuredevopslabs#600]
I´m getting this error when running the pipeline:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/RICARD~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/RICARD~1/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/RICARD~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/RICARD~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

Agent job 1
--
2 error(s), 1 warning(s)                                      PartsUnlimited-aspnet45\PartsUnlimited.DepValidation\PartsUnlimited.DepValidation.modelproj(36,11):     Error MSB4226: The imported project "C:\Program Files (x86)\Microsoft     Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"     was not found. Also, tried to find     "ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"     in the fallback search path(s) for $(VSToolsPath) - "C:\Program Files     (x86)\MSBuild\Microsoft\VisualStudio\v16.0" . These search paths are     defined in "C:\Program Files (x86)\Microsoft Visual     Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe.Config".     Confirm that the path in the <Import> declaration is correct, and     that the file exists on disk in one of the search paths.                                       Process 'msbuild.exe' exited with code '1'. | 2 error(s), 1 warning(s) |   | PartsUnlimited-aspnet45\PartsUnlimited.DepValidation\PartsUnlimited.DepValidation.modelproj(36,11):     Error MSB4226: The imported project "C:\Program Files (x86)\Microsoft     Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"     was not found. Also, tried to find     "ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"     in the fallback search path(s) for $(VSToolsPath) - "C:\Program Files     (x86)\MSBuild\Microsoft\VisualStudio\v16.0" . These search paths are     defined in "C:\Program Files (x86)\Microsoft Visual     Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe.Config".     Confirm that the path in the <Import> declaration is correct, and     that the file exists on disk in one of the search paths. |   | Process 'msbuild.exe' exited with code '1'.
2 error(s), 1 warning(s)
  | PartsUnlimited-aspnet45\PartsUnlimited.DepValidation\PartsUnlimited.DepValidation.modelproj(36,11):     Error MSB4226: The imported project "C:\Program Files (x86)\Microsoft     Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"     was not found. Also, tried to find     "ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"     in the fallback search path(s) for $(VSToolsPath) - "C:\Program Files     (x86)\MSBuild\Microsoft\VisualStudio\v16.0" . These search paths are     defined in "C:\Program Files (x86)\Microsoft Visual     Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe.Config".     Confirm that the path in the <Import> declaration is correct, and     that the file exists on disk in one of the search paths.
  | Process 'msbuild.exe' exited with code '1'.

</body>

</html>

**Comment by sriramdasbalaji** [comment]
Hi @ricardosas ,

Please try build with agent pool vs2017-win2016
![image](https://user-images.githubusercontent.com/13716984/147459684-7a125f85-32c3-4934-8aae-78a1208f7fc7.png)

And please let us know the lab where you are facing this issue.

Thanks

**Comment by ricardosas** [comment]
The Lab is this one: https://azuredevopslabs.com/labs/azuredevops/continuousintegration/

Which one are the steps for selecting the agent vs2017-win2016?

**Comment by sriramdasbalaji** [comment]
Hi @ricardosas ,

Edit your pipeline and select as shown below
![image](https://user-images.githubusercontent.com/13716984/147460636-4455749a-da9e-483f-95de-9726ff4ba019.png)

Thanks

**Comment by ricardosas** [comment]
Thanks, now it worked!
