### ISSUE TITLE
Terraform deployment fails with the given instructions

### ISSUE THREAD

**Issue by maheshcheetirala** [microsoft/azuredevopslabs#618]
Lab instructing about terrafom CICD fails with terraform init stage error.

Followed the instructions from lab , stil
![terraform error](https://user-images.githubusercontent.com/44243235/160276818-a0a71155-aae7-424a-920d-bd427bc9a6a5.png)
l could not understand the issue.

**Comment by maheshcheetirala** [comment]
https://github.com/microsoft/azuredevopslabs/tree/master/labs/vstsextend/terraform lab link and changed the agent as well still same error.

**Comment by sriramdasbalaji** [comment]
Hi,
Select Replace tokens task and do the below changes
![image](https://user-images.githubusercontent.com/13716984/165312362-20758028-0567-42a1-a57f-bb3c9710eb56.png)

This should fix the issue. We will update in the demo generator template

Thanks
