### ISSUE TITLE
Docker Registry service connection details not specified

### ISSUE THREAD

**Issue by maheshcheetirala** [microsoft/azuredevopslabs#619]
Even after adding secrets and following the instructions lab is failing.

![akserror](https://user-images.githubusercontent.com/44243235/160287604-3b53c7bd-feec-4148-86a5-2257ef293d5e.png)

**Comment by sriramdasbalaji** [comment]
Hi,

Please check if you have updated ACr details in Exercise2- Step5.

Thanks

**Comment by sriramdasbalaji** [comment]
Hi,

Closing this issue for now. Feel free to reopen if the issue still exists.

Thanks
