### ISSUE TITLE
http://cdrm-pu-demo-dev.azurewebsites.net gone

### ISSUE THREAD

**Issue by stevecrisci2** [microsoft/azuredevopslabs#621]
The FabrikamFiber test refers to the URL http://cdrm-pu-demo-dev.azurewebsites.net which is no longer available.

**Comment by sriramdasbalaji** [comment]
Hi @stevecrisci2 ,

May I know the source where it is referred?

Thanks

**Comment by stevecrisci2** [comment]
i uninstalled it, however, it was in the test code.  I recall it would not pass with that url.

**Comment by sriramdasbalaji** [comment]
Hi @stevecrisci2 ,

We are closing this issue for now. As far as we know we have not referred to this URL in  azuredevopslabs. When you come across the same next time , please share more details.

Thanks
