### ISSUE TITLE
ADO blocked due to inactivity

### ISSUE THREAD

**Issue by amitans** [microsoft/azuredevopslabs#629]
Team,
Please enable my Azure portal-amitans

**Comment by sriramdasbalaji** [comment]
Hi @amitans ,

This forum is solely for questions about azuredevosplabs. Could you please provide a screenshot of your problem so that we can assist you in deciding where to post it?

Thanks

**Comment by amitans** [comment]
Thank you. Please ignore this post. I have raised another ticket.
Regards,
Amit

Amit Anshu, PMP(r) CSM(r) Prosci(r)Certified Change Practioner
Principal Project Manager, Industry Solutions- Azure Cloud & AI
Phone: 513-208-0242
Email: ***@***.******@***.***>
Calendar: View my ***@***.***/77a5ae7e4be64644b39fb30bc1c015cc6149564271825799477/calendar.html>
***@***.***
